# 应用服务 WEB 访问端口
server:
  port: 8080

# 应用名称
spring:
  application:
    name: girl
  profiles:
    active: local
  datasource:
    dynamic:
      primary: jdbc-girl #设置默认的数据源
      datasource:
        jdbc-girl:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://110.40.195.147:3306/db_girl?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: db_girl
          password: 3iTsFJFp3rDFZFDR
      hikari:
        max-lifetime: 300000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

girl:
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
  cookie: __vtins__JNmoBsk0I91IZLwU=%7B%22sid%22%3A%20%22d19a63c7-bdfd-5b44-97da-b11d53715fa1%22%2C%20%22vd%22%3A%201%2C%20%22stt%22%3A%200%2C%20%22dr%22%3A%200%2C%20%22expires%22%3A%201676953382790%2C%20%22ct%22%3A%201676951582790%7D; __51uvsct__JNmoBsk0I91IZLwU=1; __51vcke__JNmoBsk0I91IZLwU=89fa4fd1-e51e-5988-9c58-7edcc8d0d595; __51vuft__JNmoBsk0I91IZLwU=1676951582795; gcha_sf=1676951587; __vtins__JNmlfXHHIrHMZgLq=%7B%22sid%22%3A%20%229e0073cf-1488-5d92-b1ed-8f9f92be0b88%22%2C%20%22vd%22%3A%201%2C%20%22stt%22%3A%200%2C%20%22dr%22%3A%200%2C%20%22expires%22%3A%201676953397973%2C%20%22ct%22%3A%201676951597973%7D; __51uvsct__JNmlfXHHIrHMZgLq=1; __51vcke__JNmlfXHHIrHMZgLq=e8d9ecdd-6ce3-5d0a-85bb-7fc6b8e4a1b3; __51vuft__JNmlfXHHIrHMZgLq=1676951597977; jpx=7
  #existStillSave: false
  proxy: true
